### ISSUE TITLE
About skins

### ISSUE THREAD

**Issue by Pokye** [Casual-Ragnarok/ro-docs#1]
Hello @CasualRO, first I want to congratulate you on the excellent work.
I was looking at your website, and I came across these skins, do you happen to know who the author is?
I would like to know what the name of the font he used was, and if there is a newer version of this theme.
![image](https://github.com/Casual-Ragnarok/ro-docs/assets/98105181/d5112542-e326-4573-9339-e0d01e313a70)
(https://docs.ragnarok.buzz/03-players/皮肤面板/index.html)

**Comment by CasualRO** [comment]
> Hello @CasualRO, first I want to congratulate you on the excellent work.
> I was looking at your website, and I came across these skins, do you happen to know who the author is?
> I would like to know what the name of the font he used was, and if there is a newer version of this theme.
> ![image](https://github.com/Casual-Ragnarok/ro-docs/assets/98105181/d5112542-e326-4573-9339-e0d01e313a70)
> (https://docs.ragnarok.buzz/03-players/皮肤面板/index.html)
> 

 Aurora Age: https://auroralabs.cc

**Comment by Pokye** [comment]
> > Hello @CasualRO, first I want to congratulate you on the excellent work.
> > I was looking at your website, and I came across these skins, do you happen to know who the author is?
> > I would like to know what the name of the font he used was, and if there is a newer version of this theme.
> > ![image](https://private-user-images.githubusercontent.com/98105181/293589980-d5112542-e326-4573-9339-e0d01e313a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzkzNzIsIm5iZiI6MTcwNDI3OTA3MiwicGF0aCI6Ii85ODEwNTE4MS8yOTM1ODk5ODAtZDUxMTI1NDItZTMyNi00NTczLTkzMzktZTBkMDFlMzEzYTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEwNTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTQ3ODYxZjgxYTQwYmI1MTAyYzJlN2JjZGQ2NGYwMDEyNTI4ZmQ4Y2Y5OTVjODJkZGIyMjRjZDI1MzRjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kHBdv9tzF7cDBNRkUJMXggJGYAqur1RfM-_4kPNJnWU)
> > ([https://docs.ragnarok.buzz/03-players/皮肤面板/index.html](https://docs.ragnarok.buzz/03-players/%E7%9A%AE%E8%82%A4%E9%9D%A2%E6%9D%BF/index.html))
> 
>  Aurora Age: https://auroralabs.cc

It's not the same :/

**Comment by CasualRO** [comment]
> > > Hello @CasualRO, first I want to congratulate you on the excellent work.
> > > I was looking at your website, and I came across these skins, do you happen to know who the author is?
> > > I would like to know what the name of the font he used was, and if there is a newer version of this theme.
> > > ![image](https://private-user-images.githubusercontent.com/98105181/293589980-d5112542-e326-4573-9339-e0d01e313a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzkzNzIsIm5iZiI6MTcwNDI3OTA3MiwicGF0aCI6Ii85ODEwNTE4MS8yOTM1ODk5ODAtZDUxMTI1NDItZTMyNi00NTczLTkzMzktZTBkMDFlMzEzYTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEwNTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTQ3ODYxZjgxYTQwYmI1MTAyYzJlN2JjZGQ2NGYwMDEyNTI4ZmQ4Y2Y5OTVjODJkZGIyMjRjZDI1MzRjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kHBdv9tzF7cDBNRkUJMXggJGYAqur1RfM-_4kPNJnWU)
> > > ([https://docs.ragnarok.buzz/03-players/皮肤面板/index.html](https://docs.ragnarok.buzz/03-players/%E7%9A%AE%E8%82%A4%E9%9D%A2%E6%9D%BF/index.html))
> > 
> >  Aurora Age: https://auroralabs.cc
> 
> It's not the same :/

https://exp-blog.com/game/ro/ro-bi-ji-ui-huan-fu/

may be you want

**Comment by Pokye** [comment]
Thanks <3
